### PR TITLE
Implement changes to send data upstream to the edges

### PR DESCRIPTION
**Pull request by jaztec**

### CODE REVIEW

**Comment by curry684** [comment]
I like the implementation in general, but pretty sure I do not want to expose the processing time to the platform - that should be managed by the infrastructure. And if we put it in "temporarily" now it'll be in there until 2039.

**Comment by curry684** [comment]
Thing is actually - we should reverse this. The entity should emit that it has pending changes, and the surrounding code should periodically pick up changes "at its discretion". The platform layer itself has no right to push into the outer infra.

First implementation could just always pick up immediately. Can always make that part smarter whenever we want.

**Comment by jaztec** [comment]
But that is what's already happening here right? The code changes have been made in the sandbox. The entity propagates it's changes upwards to the platform. And that's the one that uses a timer to send the messages into the channels.

What would you suggest? That the sandbox notifies the proxy of pending changes leaving it up to the proxy to flush the queue?

**Comment by curry684** [comment]
👍

**Pull request merged**
